AWSTemplateFormatVersion: '2010-09-09'
Description: Windows Instance Template

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the key pair to decrypt the Windows instance password
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC ID
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select the Subnet ID
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Select one or more Security Group IDs
  LatestWindowsAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: The latest Windows AMI ID
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base

Resources:
  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - WindowsInstanceRole

  WindowsInstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "Windows-client-${AWS::StackName}"
      Roles:
        - WindowsInstanceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: "*"
    DeletionPolicy: Delete
  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref Subnet
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance
